// Generated by CodiumAI
// src/setupTests.js
import React from 'react';
import { render, screen, fireEvent } from '@testing-library/react';
import Accordion from './Accordion'; // Import your Accordion component

import '@testing-library/jest-dom'; // Import jest-dom for additional assertions (optional but recommended)


describe('code snippet', () => {

    // Renders the accordion with the given headers and default content
    it('should add new header', () => {

      const headers = ['Header 1', 'Header 2'];
      
      const { rerender, getByText } = render(<Accordion headers={headers} />);
      
      const addButton = getByText('Add Header');
      
      fireEvent.click(addButton);
    
      rerender(
        <Accordion  
          headers={[...headers, 'New Header 3']}
        />
      );
    
      expect(getByText(/New Header 3/i)).toBeInTheDocument();
    
    });
    });
